version: "3.3"
services:
    master:
        build:
            context: ./jenkins-master
            args:
                - PROXY=${PROXY}
                - JENKINS_VERSION=${JENKINS_VERSION}
                - JENKINS_SHA=${JENKINS_SHA}
                - JAVA_OPTS=${JAVA_OPTS}
                - JENKINS_OPTS=${JENKINS_OPTS}
        ports:
            - "50000:50000"
            - "8080:8080"
        volumes:
            - ./jenkins-master/data/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - ./jenkins-master/log/jenkins:/var/log/jenkins
            - ./jenkins-master/plugins.txt:/tmp/plugins.txt
            - ./jenkins-master/plugins.sh:/usr/local/bin/plugins.sh
            - ./jenkins-master/init.groovy:/usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy
            - ./jenkins-master/certs:/usr/local/etc/jenkins/certs
        command: >
            bash -c "
                /usr/local/bin/plugins.sh /tmp/plugins.txt;
                rsync -rltvzO /usr/share/jenkins/ref/ /var/jenkins_home;
                find /var/jenkins_home/plugins -name "*.jpi" -exec touch {}.pinned \;
                exec java ${JAVA_OPTS} -jar /usr/share/jenkins/jenkins.war ${JENKINS_OPTS};
                RUN chmod +r /usr/local/etc/jenkins/certs/ca.pem;
                RUN chmod +r /usr/local/etc/jenkins/certs/cert.pem;
                RUN chown -R jenkins:jenkins /usr/local/etc/jenkins;
                RUN chmod 777 /var/run/docker.sock"
    nginx:
        build:
            context: ./jenkins-nginx
            args:
                - PROXY=${PROXY}
        ports:
            - "9090:80"
        volumes:
            - ./jenkins-nginx/conf/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
            - ./jenkins-nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - master
        command: nginx
    slave:
        build: jenkins-slave
        dns:
            - 8.8.8.8
            - 9.9.9.9
        command: ["/usr/sbin/sshd","-D"]
